/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../MobileApp/src/index`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/app/discover`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/app/signup`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/scripts/reset`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/scripts/seed`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/providers/AppProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/providers/FontProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/providers/LocalStorageProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/providers/ThemeProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/config/tamagui.config`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/config/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/config/fonts`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../MobileApp/src/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../MobileApp/src/app/discover`; params?: Router.UnknownOutputParams; } | { pathname: `/../MobileApp/src/app/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../MobileApp/src/app/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/../MobileApp/src/scripts/reset`; params?: Router.UnknownOutputParams; } | { pathname: `/../MobileApp/src/scripts/seed`; params?: Router.UnknownOutputParams; } | { pathname: `/../MobileApp/src/providers/AppProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/../MobileApp/src/providers/FontProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/../MobileApp/src/providers/LocalStorageProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/../MobileApp/src/providers/ThemeProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/../MobileApp/src/config/tamagui.config`; params?: Router.UnknownOutputParams; } | { pathname: `/../MobileApp/src/config/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/../MobileApp/src/config/fonts`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../MobileApp/src/index${`?${string}` | `#${string}` | ''}` | `/../MobileApp/src/app/discover${`?${string}` | `#${string}` | ''}` | `/../MobileApp/src/app/index${`?${string}` | `#${string}` | ''}` | `/../MobileApp/src/app/signup${`?${string}` | `#${string}` | ''}` | `/../MobileApp/src/scripts/reset${`?${string}` | `#${string}` | ''}` | `/../MobileApp/src/scripts/seed${`?${string}` | `#${string}` | ''}` | `/../MobileApp/src/providers/AppProvider${`?${string}` | `#${string}` | ''}` | `/../MobileApp/src/providers/FontProvider${`?${string}` | `#${string}` | ''}` | `/../MobileApp/src/providers/LocalStorageProvider${`?${string}` | `#${string}` | ''}` | `/../MobileApp/src/providers/ThemeProvider${`?${string}` | `#${string}` | ''}` | `/../MobileApp/src/config/tamagui.config${`?${string}` | `#${string}` | ''}` | `/../MobileApp/src/config/firebaseConfig${`?${string}` | `#${string}` | ''}` | `/../MobileApp/src/config/fonts${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../MobileApp/src/index`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/app/discover`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/app/signup`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/scripts/reset`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/scripts/seed`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/providers/AppProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/providers/FontProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/providers/LocalStorageProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/providers/ThemeProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/config/tamagui.config`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/config/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/../MobileApp/src/config/fonts`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
